### ISSUE TITLE
[FEATURE] Add GMS free variant

### ISSUE THREAD

**Issue by Myzel394** [Myzel394/locus#10]
Follow-up from #7

**Comment by Myzel394** [comment]
> Alternatively, keep the same applicationId for both and just name the APK files differently at releases/ so I know which one to pick

@IzzySoft I think this would be the easiest way both for me and for the users. I'll do a check within the app to check whether GMS is available and will then show a dialog to the users asking them if they want to change (if they use the GMS but have no GMS on the OS)

**Comment by IzzySoft** [comment]
That sounds like a good plan. And as long as you don't need any non-free dependency for that, maybe also vice-versa (a la "if you have issues with location …"). Only problem I could see with that is: if someone with the GMS version installed uses my repo and follows the update notification (which will be shown, as `applicationId` and signature match), they will be switched to the FOSS version again. Easy to fix of course, they'd just need to install the GMS version on top again.

**Comment by Myzel394** [comment]
> Only problem I could see with that is: if someone with the GMS version installed uses my repo and follows the update notification (which will be shown, as applicationId and signature match), they will be switched to the FOSS version again. Easy to fix of course, they'd just need to install the GMS version on top again.

Is there a way for the app to signal what version it is?

**Comment by Myzel394** [comment]
I just found out that https://gitlab.com/hanntech-gmbh/free2pass/flutter-geolocator-floss only seems to be supporting geolocator `7.6.2` (newest version is `9.0.2`), which is already 2 years old. I'd prefer not to install such an old version. I'll rather learn someday how to use create my own Android bridge to fetch the location without Google.

**Comment by IzzySoft** [comment]
> Is there a way for the app to signal what version it is?

Using a different icon maybe?

> only seems to be supporting geolocator `7.6.2`

I knew there was a catch (that's what I referred to when stating my snippet might not be up-to-date there). I vaguely remember there was some other patch fixing that problem. Unfortunately I forgot to add that then. Hm, a quick search brought up this issue in the geolocator repo: [No google services compile option](https://github.com/Baseflow/flutter-geolocator/issues/841) – note the microG option (if you don't know [microG](https://github.com/microg): it's a FOSS replacement of the proprietary GMS stuff). Maybe that could be accomplished by a patch? I'm no Android dev, so I'm not sure. I also don't know if Max (and [his company](https://github.com/orgs/digitalfabrik)) went on to create that fork/Maven artifact – it's quite a while ago I last spoke with him. Didn't find any "`*geo*` project in his account, just maplibre (they'd need it for their [Ehrenamts app](https://github.com/digitalfabrik/entitlementcard/tree/main/frontend); seems they use the original package and just overlay `geolocator_android` ([commit that introduced this](https://github.com/digitalfabrik/entitlementcard/commit/04702572feb7e92c823c1bb0d22b7dabcbe1e09b)) from a different source now).

**Comment by Myzel394** [comment]
Okay so https://github.com/Zverik/every_door/blob/aaf8d2fdeac483041bcac2c7c79ef760b99dff2b/pubspec.yaml#L55 uses the latest version of `geolocator`, meaning that we can use this for the non-gms variant. That means we'll create two flavors: `gms` and `floss`. Now I only need to find out how to detect the flavor on Flutter. [This answer from StackOverflow recommends setting a build environment variable](https://stackoverflow.com/a/65315937/9878135). This would be absolutely no problem since all the APKs are built via the CI:CD. But I was wondering if there are any disadvantages using that, @IzzySoft do you know if there are any? If not, I'll go with that.

**Comment by Myzel394** [comment]
@IzzySoft taken from [your comment](https://github.com/Myzel394/locus/issues/7#issuecomment-1561756854):

> I've checked the YAML in F-Droid's metadata, suspecting some sed magic – but couldn't spot any related (there is some sed, but not for geolocator). The only ones I see are:

      - sed -i -e 's/^#f//' pubspec.yaml
      - sed -i -e 's/^\(.*\bMultiDex\b\)/\/\/ \1/' android/app/src/main/java/io/flutter/app/FlutterMultiDexApplication.java
      - echo '{}' > lib/l10n/app_zh.arb
      - export PUB_CACHE=$(pwd)/.pub-cache
      - vendor/flutter/bin/flutter config --no-analytics
      - vendor/flutter/bin/flutter packages pub get

where did you find this? I can't find this in the [workflow file](https://github.com/Zverik/every_door/blob/main/.github/workflows/build-apk.yml)

**Comment by IzzySoft** [comment]
> do you know if there are any? 

Sorry, no – I'm no Android dev at all…

> where did you find this?

That's part of the F-Droid Metadata build recipe for the app. You can find it in the fdroiddata repo, in the `metadata/` subdir.

**Comment by Myzel394** [comment]
@IzzySoft the next release will include both the GMS and FLOSS variant. I have also simplified the names. If I'm not mistaken, we are currently using `armeabi`, aren't we? In that case, your store needs to grab a file called `locus-armeabi-floss.apk`. Can you change this on your side so your store grabs the correct file?

**Comment by IzzySoft** [comment]
Yes, you're right there. And thanks for the forewarning: Told my updater to not just pick "any `armeabi`" in the future, but just files matching `armeabi-floss`, as you suggested. Ready to pick up the next release then! Once it is out, please remind me to remove `NonFreeDep` :smiley:

**Comment by Myzel394** [comment]
> , please remind me to remove NonFreeDep 😃

won't this happen automatically? I thought it scans the APK and then adds the flags accordingly

**Comment by IzzySoft** [comment]
> won't this happen automatically?

Not for NonFreeDep, because that I can not automatically detect in all cases. The original meaning of this anti-feature is:

> The application depends on a non-free application (e.g. Google Maps) - i.e. it requires it to be installed on the device, but does not include it.

I've "abused" it all those years to also cover "**includes** a non-free component". So if there's no non-free component, that does not necessarily mean there's no NonFreeDep – it might still depend on GMS or the likes.

That's an issue which soon will be solved, as finally (with the next release of fdroidserver), custom anti-features become available. I'm prepared for that, and as soon as the client supports it, will "split off" a new anti-feature called "NonFreeComp":

> The application includes non-free components/libraries (e.g. Firebase Cloud Messaging)

Then I'll adjust my checker accordingly, and it will be handled as the other ones (except for NonFreeDep, NonFreeAdd  and NonFreeNet), as you assumed correctly. Those 3 exceptions are the ones lying *outside* the APK, so the scanner can only guess them by some library (eg. FCM will cause NonFreeNet), but it can never be sure abou their absence (NonFreeNet can also be caused by, well, the dependency of some network connection – think e.g. of NewPipe depending on YouTube).

**Comment by Myzel394** [comment]
Okay I just checked [every-door](https://github.com/Zverik/every_door). While it does work on a GrapheneOS phone, it doesn't work on the Xiaomi phone. We'll have to stick to two flavors of the app, even if it's not the best solution :/

**Comment by Myzel394** [comment]
New release has been released, let's hope everything runs smoothly.

**Comment by IzzySoft** [comment]
Triggered manually: my updater found and pulled the APK, currently running the checks against it (library scanner, VT etc).

**Comment by IzzySoft** [comment]
OK, all through: I confirm full success, the AF has been removed (effective with the next sync around 6 pm UTC) :partying_face:
