### ISSUE TITLE
[FEATURE] Display my own track on the map on par with tracks from other devices

### ISSUE THREAD

**Issue by Korb** [Myzel394/locus#103]
**Is your feature request related to a problem? Please describe.**
In the current version of the application, only the tracks of the devices that granted me access are displayed on the map. However, I don't see my own track, only the point of my current location.

**Describe the solution you'd like**
I propose to add the ability to enable the recording of a track of one's own movements in the application settings and display it on the map with the selected color, [thickness and transparency](https://github.com/Myzel394/locus/issues/101).

**Describe alternatives you've considered**
I tried to enable tracking using the link I created myself, but my attempt was unsuccessful:

> An error occurred while importing the task
> This is a task from you (name: Share from 2023 August 31, 10:39:27).
> 

**Additional context**
The proposed functionality would be needed, for example, during search and rescue operations in the natural environment (in the forest, on large bodies of water) for the rapid assessment of the mutual movement of search groups. Of course, I don't see Locus as the main instrument for coordinating small emergency response teams. But as an auxiliary tool for rescue volunteers, it would be very convenient.

**Comment by Myzel394** [comment]
@Korb To not store an excessive amount of data, I'd propose that the App shows the current history while the app is open. This means, if you have Locus open and you move around, this movement will be shown on the map. If Locus is closed, no location will be saved, meaning you will always start with a fresh session. This behavior is also used in [StreetComplete](https://github.com/streetcomplete/StreetComplete) for example.

What do you think?

**Comment by Korb** [comment]
@Myzel394, I'm not sure I fully understand what you wrote. For example, by "an excessive amount of data" do you mean the amount of data in bytes or "collect too much data about user behavior"? In both cases, the final decision about saving your own movements can be left to the user. It was convenient for me to write a report on my long trip, having data on my movements for each day of the trip in Google Maps Timeline.

I don't know what you mean by session. I am quite happy if the application runs continuously while the smartphone is on. This is the mode I used to use Google Maps Location History in for years.

Now about "save only when Locus is open". Agree that the functionality of the application is quite limited (and this is normal), and in most cases the user is satisfied with stable, non-interactive background operation of the application. Because the main activity of the user at this time (regardless of the method of movement) is focused on communication, navigation application, multimedia player, reading, etc.
