### ISSUE TITLE
[BUG] Unable to disable "Share" on the "Shares Overview" screen

### ISSUE THREAD

**Issue by Korb** [Myzel394/locus#105]
## OS

* [X] Android
* [ ] iOS

## Android specific
* [ ] Samsung Android (Samsung Phones)
* [ ] MIUI (Xiaomi Phones)
* [ ] Stock ROM (Google Phones)
* [ ] Huawei Android (Huawei Phones)
* [ ] GrapheneOS
  * [ ] I do have Google Play Services installed
* [ ] LineageOS
* [X] Funtouch OS 13 Global

## Describe the bug
Pressing the enabled switch causes the message "Task stopped. The task has been stopped and will start again at September 2, 06:00" to briefly appear at the bottom of the screen. The switch remains on.

## To Reproduce
1. Create a daily on/off schedule for "Shares". The current time and day must match the on period.
2. On the "Shares Overview" screen, try turning off this "Share".

## Expected behavior
"Share" is turned off, but the schedule for turning it on and off is preserved (not deleted, but inactive). In order for "Share" to turn on and off again according to the schedule, it must be turned on again on the "Shares Overview" screen. That is, "Shares" should have two independent switches: "on" / "off" and "transmitting data" / "not transmitting data".

## Screenshots
![Screenshot_2023_0901_193505_app myzel394 locus](https://github.com/Myzel394/locus/assets/3509797/f9ebbc3d-8706-425a-959e-14a5cc069f56)

## Additional context
OS version: Funtouch OS 13 Global
Model: Vivo T1 (4G, V2153)
Hardware version: MP_0.1
Build number: PD2201OF_EX_A_13.1.15.6.W20.V000L1
Baseband version: MPSS.HA.1.1.c2-00012-KD_ALL_PACK-1.6347.120
Kernel version: 4.19.157-perf+. 1 Fri Aug 4 19:33:15 CST 2023
Compile time: 4 Aug 2023 13:39:16
Android security update: 1 August 2023
Google Play system update: 1 July 2023

## App Version
locus-arm64-gms.apk

**Comment by Myzel394** [comment]
What timers are you using on this share?

**Comment by Korb** [comment]
> Monday 05:30 - 23:00
> Tuesday 05:30 - 23:00
> Wednesday 05:30 - 23:00
> Thursday 05:30 - 23:00
> Friday 05:30 - 23:00
> Saturday 05:30 - 23:00
> Sunday 05:30 - 23:00
