### ISSUE TITLE
[BUG] Text does not fit in Notification Shade

### ISSUE THREAD

**Issue by Korb** [Myzel394/locus#106]
## OS

* [X] Android
* [ ] iOS

## Android specific
* [ ] Samsung Android (Samsung Phones)
* [ ] MIUI (Xiaomi Phones)
* [ ] Stock ROM (Google Phones)
* [ ] Huawei Android (Huawei Phones)
* [ ] GrapheneOS
  * [ ] I do have Google Play Services installed
* [ ] LineageOS
* [X] Funtouch OS 13 Global

## Describe the bug
Currently, the text on the Notification Shade looks something like this:

> Locus • 11h
> Updating location in real-time
> Close Locus to stop sharing in real time. Locus will still upda..

## To Reproduce
1. Create "Share", enable it
2. Switch to desktop or another application
3. Open Notification Shade

## Expected behavior
Rephrase the text of the notification to a shorter one, make the third line in the form of a ticker, or implement the ability to expand the notification vertically to read the notification text in full.

## Screenshots
![Screenshot_20230901_190415](https://github.com/Myzel394/locus/assets/3509797/8b76921c-c29e-4fdd-b54d-1edfc7588e3a)

## Additional context
OS version: Funtouch OS 13 Global
Model: Vivo T1 (4G, V2153)
Hardware version: MP_0.1
Build number: PD2201OF_EX_A_13.1.15.6.W20.V000L1
Baseband version: MPSS.HA.1.1.c2-00012-KD_ALL_PACK-1.6347.120
Kernel version: 4.19.157-perf+. 1 Fri Aug 4 19:33:15 CST 2023
Compile time: 4 Aug 2023 13:39:16
Android security update: 1 August 2023
Google Play system update: 1 July 2023

## App Version
locus-arm64-gms.apk

**Comment by Myzel394** [comment]
Yeah I already noticed that but I'm not sure how to resolve this unfortunately :C Some Android roms show more two lines while others only show one
