### ISSUE TITLE
[FEATURE] Sorting the Nostr Relays List

### ISSUE THREAD

**Issue by Korb** [Myzel394/locus#107]
**Is your feature request related to a problem? Please describe.**
Currently, the list of Nostr Relays is an unsorted sequence:

- tw.purplerelay.com
- nostr.bg
- relay.nostriches.org
- welcome.nostr.wine
- relayable.org
- wine.relay.center
- nostr-01.bolt.observer
- free.nostr.lc.
- tmp-relay.cesc.trade
- relay,humanumest.social
- nostr-badur.onrender.com
- nostr.mom
- no.str.cr
- nostr.truckenbucks.com
- relay-pub.deschooling.us
- relay.damus.io
- nostr.zenon.info
- lamp.wtf
- relay.f7z.io
- nostr-rs-relay.phamthanh.me
- nostr.orangepill.dev
- nostr.klabo.blog
- nostr.supremestack.xyz
- relays.nostr.bg
- n.xmr.se
- nostr.nodeofsven.com
- newtest.relaying.io
- nos.lol
- eden.relay.center
- btc.klendazu.com
- relap.orzv.workers.dev
- saltivka.org
- nostr-relay.app
- nostr.kmchu.net
- nostr.irrelevant.mooo.com
- realy.nostr.bg
- nostr.getgle.org
- relay2.nostr.vet
- relay.shroomslab.net
- nostr.einundzwanzig.space
- nostr.f4255529.shop
- nostrue.com
- lingoh.dev
- relay.flurs.art
- nostr.openordex.org
- bitcoinmaximalists.online
- relay.valera.co
- sg.qemura.xyz
- nostr.plebchain.org
- relay.nostr.nu
- ithurtswhenip.ee
- nostr.cro.bar
- nostr.simplex.icu
- nostr.pinkanki.org
- nostr.thesamecat.io
- relay.nostromo.social
- nostr.itas.li
- relar.nostr.bg
- nopo.shroomslab.net
- relay.nostrigator.com
- africa.nostr.joburg
- nest.nostr1.com
- nostr.21 m.fr
- shroomslab.net
- nostr.strits.dk
- relay.nostr.ro
- saltivka.org
- nostr.bitcoiner.social
- nostr.gruntwerk.org
- nostr.middling.mydns.jp
- dash.nostr.neuropix.de
- xn--relao-dra1 a.nostr.bg
- snort.relay.center
- nostr.dncn.xyz
- nostr.zbd.gg
- relay.primal.net
- nostr.vulpem.com
- feeds.nostr.band
- relayl.nostrchat.io
- nostr.openhoofd.nl
- relay.nostr.com.au
- nostr.rocks
- atl.purplerelay.com
- nostr.foundrydigital.com
- relay.relayable.org
- therelayofallrelays.nostrl.com
- relay.nostr.rocks
- relay.nostr.moctane.com
- he.relayable.org
- ca.orangepill.dev
- nostr.globals.fans
- la.relayable.org
- paid.spore. ws
- slick.mjex.me
- relay.nostrich.de
- hotrightnow.nostr!.com
- relay.nostrswap.com
- relayoi.karma,svaha-chain.online
- nostr.maximacitadel.org
- bitcoinforthe.lol
- relay.nostr.mn
- nostr.topeth.info
- relay.snort.social
- earn-design-distinct- competition.trycloudflare.com
- welcome.nostr.wine.
- nostrl.current.fyi
- nostr.wine
- nostr.roundrockbitcoiners.com
- nostr.w3ird.tech
- e.nos.lol
- nostr-02.dorafactory.org
- relay.nostr.bg
- nostr.screaminglife.io
- relay.hamnet.io
- relay.conxole.io
- nsc.pleb.cloud
- nostr.zkid.social
- relay.nostr.band
- relay.plebstr.com
- nostr.oxtr.dev
- relay.deezy.io
- foolay.nostr.moe
- relay.poster.place
- relay.bitransfer.org
- roy-gem-arbitration-suits.trycloudflare.com
- au.relayable.org
- nostr-us.coinfundit.com
- relay.red
- relay.orangepill.dev
- relay2.nostrchat.io
- relay.farscapian.com
- relay.mostr.pub
- nostr.thomascdnns.com
- nostr21.com
- nostr-pub1.southflorida.ninja
- nostr.swiss-enigma.ch
- nostr.cheeserobot.org
- nostr-01.yakihonne.com
- free.nostr.lc
- test.nostr.lc
- relay.nostr.wirednet.jp
- za.purplerelay.com
- nostr-relay.nokotaro.com
- nostrrelay.geforcy.com
- nostr.milou.lol
- nostr-rs-relay.cryptoassetssubledger.com
- zee-relay.fly.dev
- relay.austrich.net
- n-word.sharivegas.com
- ca.relayable.org
- relayl.nostrswap.com
- lightningrelay.com
- damus.relay.center
- relay.ingwie.me
- bitcoiner.social
- supertestnet.nostrl.com
- offchain.pub
- nostr.dakukitsune.ca
- nostrsatva.net
- relai.nostr.bg
- a.nos.lol
- nostr.ingwie.me
- relay.mostr.pub.
- relay.nostr.vet
- relay.nostr.band
- relay.sendstr.com
- relay.shitforce.one
- nostr.nicfab.eu
- nostr.koutakou.tech
- nostr.frennet.xyz
- nostr.noones.com
- nostr.sidnlabs.nl
- bevo.nostr1.com
- tomt.relaying.io
- nproxy.kristapsk.lv
- nostr.wine
- really.nostr.bg
- nostr.beta3.dev
- spore. ws
- eden.nostr.land
- relay.damus.io
- relay.nostrplebs.com
- relay.cryptocculture.com
- relay-verified.deschooling.us
- nostr.relayable.org
- nostr.filmweb.pl
- relay.nostrassets.com
- in.purplerelay.com
- beta.nostril.cam
- nostr-relay.schnitzel. world
- powrelay.xyz
- soloco.nl
- eu.purplerelay.com
- nostr.1f52b.xyz
- nostr.mouton.dev
- nl.nostr.wine
- relay.queiroz.vip
- relay.toastr.space
- nostro.online
- ts.relays.world
- purplepag.es
- nostr-1.nbo.angani.co
- nostr.massmux.com
- nb.relay.center
- proxy.shroomslab.net
- nostr3.actn.io
- nostr.bitcoinplebs.de
- purplerelay.com
- yabu.me
- nostr-verif.slothy.win
- jp.nostr.wine
- offchain.relay.center
- stealth.wine
- nostr.yuv.al
- nostr.thezap.club
- relay.2nodez.com
- nostr.lingoh.dev
- nostr.shroomslab.net
- nostr.notmyhostna.me

(possible OCR errors)

**Describe the solution you'd like**
I propose to sort this list alphabetically. Or, better, like Proxy servers in Telegram clients - in ascending ping. Moreover, currently inactive Relays should be displayed last, at the end of the list.

**Comment by Myzel394** [comment]
The list is shuffled each time its loaded to not favor some relays. However, some relays seem to not properly work. Because of that, I was thinking about adding like a social credit system for relays to figure out which relays are working and which aren't.

> Or, better, like Proxy servers in Telegram clients - in ascending ping

We'd have to ping each relay, which would be a massive amount of network requests. I don't like to do that.

> Moreover, currently inactive Relays should be displayed last, at the end of the list.

Originally, only active relays were shown. However, it looks like the api for that is down currently. All relays are shown instead at the moment
