### ISSUE TITLE
[FEATURE] Explanations of the need for each of the permissions requested by the app

### ISSUE THREAD

**Issue by Korb** [Myzel394/locus#112]
I propose to place in README.md a separate list of explanations why this application needs the permissions it requests. In the case of 0.14.3 these are "**Location**", "**Notifications**", "**Nearby devices**" and "**Phone**".

Many users do not pay attention to the fact that some “Flashlight” or “Calculator” wants access to location, and sending paid SMS, and collecting statistics on the use of other applications, and so on. However, without taking a closer look at the app's capabilities, many permissions are actually needed, even if it's not obvious. You can easily allay the suspicions of such users by mapping all permissions to the app features that use them.

**Comment by Myzel394** [comment]
Permissions are only requested when they are required and Locus then shows an explanation in the app itself on why they are required.
