### ISSUE TITLE
F-Droid listing

### ISSUE THREAD

**Issue by IzzySoft** [Myzel394/locus#117]
Your app reached F-Droid on 2023-08-17 – but your Readme still points to my repo. At this point I'd usually remove the app here, but with your Readme linking here that would cause some confusion because of the resulting 404. So would you replace the badge then with F-Droid's and link there instead?

**Comment by Myzel394** [comment]
Good catch, I'll add the F-Droid badge! 

> but with your Readme linking here that would cause some confusion because of the resulting 404

I'm a bit confused - when I click on the badge, it leads me to your website. Do you want to remove Locus from your repo?

**Comment by IzzySoft** [comment]
> Good catch, I'll add the F-Droid badge!

:+1:

> I'm a bit confused - when I click on the badge, it leads me to your website.

Yes, it's still there – because you still have the badge on your Readme, I didn't yet remove it.

> Do you want to remove Locus from your repo?

Usually, as soon as an app gets available at F-Droid.org I remove it from my repo (after a little overlap of ~2 weeks). My repo runs on personal space, so I try to keep it slim (and Locus is already close to the "30 MB per app" limit with its current "27 MB per APK"). Further, your app has not established reproducible builds with F-Droid, so this could cause some confusion with the listings (as cross-updates are not possible; and with my repo usually being updated faster, folks might unintentionally install it from here though they preferred it from the "more trusted" source of F-Droid.org).

Exceptions are possible (so when explicitly asked to keep it, I can mark apps such and keep them), but should stay exceptions. Size and the signature differences here would make a removal from my repo probably be preferable – we'd run into the next issue when your APK size goes beyond the 30 MB limit anyway. What do you think?

**Comment by Myzel394** [comment]
> What do you think?

I've removed your badge, you can remove Locus from your repo

**Comment by IzzySoft** [comment]
Thanks! Will be gone then with the next sync around 6 pm UTC. Should you need it back there for some reason later please let me know and we can check. And all the best for you and your development – I've enjoyed working with you!

**Comment by Korb** [comment]
> No versions with compatible signer

Is the lack of any versions of this app on its F-Droid page related to the issue discussed here?

**Comment by Myzel394** [comment]
> Is the lack of any versions of this app on its F-Droid page related to the issue discussed here?

I'm not sure what you mean; Locus is listed on F-Droid with the latest version 0.15.2 https://f-droid.org/packages/app.myzel394.locus/

**Comment by Korb** [comment]
![Screenshot_20231111_163838_org fdroid fdroid](https://github.com/Myzel394/locus/assets/3509797/d7117ab4-e34d-42fe-99b7-e1c5258e6984)

![Screenshot_2023_1111_163856_org fdroid fdroid](https://github.com/Myzel394/locus/assets/3509797/667301e9-1345-4f70-8ac6-27c618373d4d)

**Comment by Myzel394** [comment]
@Korb that's peculiar. I don't see this on my phone. Did you change something in the settings?

**Comment by Korb** [comment]
@Myzel394, I haven't changed the list of repositories connected to the F-Droid app, if that's what you mean. Just updated them. Other apps installed through the F-Droid app are now updating normally. The monthly security update for the OS was recently installed. I don't know if this could have had an impact?

**Comment by IzzySoft** [comment]
@Korb where did you install the app from originally? Most likely from my repo, where the APKs were signed by @Myzel394. As with the inclusion at F-Droid.org reproducible builds were NOT established, APKs there are signed by F-Droid. Now Locus was removed from my repo (as it reached F-Droid), thus: "no versions with compatible signers". Can't be helped: you'll have to uninstall and re-install from F-Droid.
