### ISSUE TITLE
[FEATURE] Do not track location when airplane mode is on

### ISSUE THREAD

**Issue by TechD123** [Myzel394/locus#129]
**Is your feature request related to a problem? Please describe.**
While battery saver mode is great, there should be something more absolute to save more battery.

**Describe the solution you'd like**
Some users may prefer to not have the app try to update the location while in airplane mode. There could be a toggle for this in settings.

**Additional context**
PhoneTrack (from F-Droid) already does this.

**Comment by Myzel394** [comment]
This makes sense, will add that!
