### ISSUE TITLE
[FEATURE] In case of a long list of Timers, stretch it vertically

### ISSUE THREAD

**Issue by Korb** [Myzel394/locus#132]
Now (animated GIF):
![Screenshot_2023_1016_112016_app myzel394 locus copy](https://github.com/Myzel394/locus/assets/3509797/67194b27-782b-44cd-9172-c54a96aecbde)

That is, in this case there is no reason to limit the height of the list, forcing the user to scroll it.

OS version: Funtouch OS 13 Global
Model: Vivo T1 (4G) / V2153
Serial number: 10AC7P0W4L00175
Hardware version: MP_0.1
Build number: PD22010F_EX_A_13.1.15.8.W20.V000L1
Baseband version: MPSS.HA.1.1.c2-00012-KD_ALL_PACK-1.6347.120
Kernel version: 4.19.157-perf+. 1 Mon Sep 4 13:23:15 CST 2023
Compile time: 4 Sept 2023 08:11:57
Android security update: 1 September 2023
Google Play system update: 1 September 2023

**Comment by Myzel394** [comment]
Good catch, will add that!
