### ISSUE TITLE
[BUG] Location Position Inconsistent with Time

### ISSUE THREAD

**Issue by Trey10000** [Myzel394/locus#134]
## OS

* [ X] Android
* [ ] iOS

## Android specific
If you ticked `Android`, please specify on which Android flavor this issue happens

* [ ] Samsung Android (Samsung Phones)
* [ ] MIUI (Xiaomi Phones)
* [ ] Stock ROM (Google Phones)
* [ ] Huawei Android (Huawei Phones)
* [X ] GrapheneOS
  * [ X] I do have Google Play Services installed
* [ ] LineageOS

## Describe the bug
The location history for a person isn't consistent with time, they seem to teleport around and in their logs the updated time is inconsistent. Sometimes preferring their update at 8:30am to their location update at 12:30pm. Making them seem like they are teleporting around the map.

## To Reproduce
1. Go to 'FLOSS Locus app'
2. Click on 'Logs for the family member that is twitching around'
3. Scroll down to 'The bottom and notice the logs are inconsistent with time'

## Expected behavior
The app bases location history off of time not any other metric, if someone pinged they were at home around 8, then work at 12, the app shouldn't show them at work then choose the 8am one as its primary and teleport them back home.

## Priority
Please set a realistic priority on how important this issue is to you. We will fix all bugs, but urgent bugs (such as the app not starting at all for example) are more important than fixing some styles for example.

* [ ] Low
* [x] Medium
* [ ] High
* [ ] Urgent
 
## App Version
Please add the version you have installed here. You can find the version by opening Locus > Tap on the top right settings icon > Scroll completely down > At the very bottom you can find your version with your flavor, for example "Version 0.8.1 (GMS)" or "Version 0.7.0 (FLOSS)".
 "locus-arm64-floss.apk"

## Logs

 

![Screenshot_20231027-131407](https://github.com/Myzel394/locus/assets/130109876/42f45bcd-8c12-42dd-b902-6267d6f037d5)

**Comment by Myzel394** [comment]
Good catch, seems to be a small programming mistake from my side! ^^
