### ISSUE TITLE
[BUG] blackish map?

### ISSUE THREAD

**Issue by i-am-rumburak** [Myzel394/locus#139]
## OS

* [x] Android
* [ ] iOS

## Android specific
crdroid 9.11

* [x] Samsung Android (Samsung Phones)
* [ ] MIUI (Xiaomi Phones)
* [ ] Stock ROM (Google Phones)
* [ ] Huawei Android (Huawei Phones)
* [ ] GrapheneOS
  * [ ] I do have Google Play Services installed
* [x] LineageOS

## Describe the bug
the map is very dark. not sure if it is a bug or a feature.

<a href="https://ibb.co/NCZ7sFx"><img src="https://i.ibb.co/Rbz79g2/Screenshot-20231226-131006-Locus.png" alt="Screenshot-20231226-131006-Locus" border="0"></a>

## Expected behavior
maps in usual color scheme would ne nice
<a href="https://ibb.co/TMMxtPV"><img src="https://i.ibb.co/s99dqs0/Screenshot-20231226-132005-Firefox.png" alt="Screenshot-20231226-132005-Firefox" border="0"></a>

## Priority
Please set a realistic priority on how important this issue is to you. We will fix all bugs, but urgent bugs (such as the app not starting at all for example) are more important than fixing some styles for example.

* [ ] Low
* [ ] Medium
* [ ] High
* [ ] Urgent
 
## App Version
0.15.2 floss

**Comment by Myzel394** [comment]
Yep, this is intended as your device is in dark mode :D
