### ISSUE TITLE
[Important] domain locus.cfd expired!

### ISSUE THREAD

**Issue by xxxcrow** [Myzel394/locus#156]
Sorry for not following the template, but it feels like something important locus.cfd expired and now when opening it there are adds and a bar that suggests to renew the domain

**Comment by Myzel394** [comment]
Thanks for bringing this up. I'm currently unable to renew it, as the reactivation costs would be $669.50 (yes, over 600 dollars). I contacted the support of my domain registrar and hope this is just an automation issue and not the true price...

**Comment by xxxcrow** [comment]
Should be a mistake, many registrars have renewal of this domain just for around $10

**Comment by Myzel394** [comment]
`locus.cfd` is back under control! Thanks for opening the issue.
