### ISSUE TITLE
Location not being added

### ISSUE THREAD

**Issue by Lamazeva** [Myzel394/locus#31]
I'm unable to add a location to any of the tasks, even when other apps like Osmand can get my GPS, I'm on DivestOS 20.0, Android 13. Using the 0.4.1 version. 

I've tried reinstalling and restarting, to no avail!

**Comment by Myzel394** [comment]
@Lamazeva hey, what version are you using (F-Droid?), also I'm not familiar with DivestOS, do you know if you have Google Play Services installed?

**Comment by Lamazeva** [comment]
My apologies, I should have mentioned, DivestOS is a security and privacy focused ROM, Sort of like a precursor to GrapheneOS, and no, I have 0 Google Play Services or any MicroG, my F-Droid version is 1.16.3, I also tried using Locus in a work profile, but same result, there doesn't seem to be anywhere for me to put in my location in the app when making the task, or am I using it incorrectly? Other apps using Location services operate just fine.

2023-05-31T20:07:22Z Myzel394 ***@***.***>:

**Comment by Myzel394** [comment]
@Lamazeva there could be several reasons why the location is not being fetched, could you try the following?

1. Go outside (seriously :D, I had problems fetching the location when I was inside)
2. Create a new task
3. Some relays do not seem to be working - relay.damus.io was working for me, maybe you could try only selecting this relay
4. Start the task - this may take some while as this now accesses your location, but it should work

**Comment by Lamazeva** [comment]
No problem bro, I'll play around with it some more and give it a shot for the location, I'll try out that relay too, is it okay if I pick more than one relay at a time?

2023-05-31T20:25:24Z Myzel394 ***@***.***>:

**Comment by Myzel394** [comment]
@Lamazeva normally it should not be a problem, but could you use for this issue only relay.damus.io? At the moment Locus also just uses the first relay to fetch the location, but I will change that in the next releases.

I just disabled Google Play Services on my GrapheneOS phone (it's normally enabled) and I can confirm that when I'm inside, the location does not work at all but as soon as I go out, it works flawlessly.

**Comment by Myzel394** [comment]
btw you can test the location by long pressing on the icon on the home launcher and then tapping on "Update location now" - this might be easier for you to test it out :D

**Comment by Myzel394** [comment]
> relay.damus.io as a default relay, im not sure which of the two actions fixed it, but it seems to have worked instantly!

I think it was the relay. I'll have to check which relays work with Locus and which don't.

**Comment by Lamazeva** [comment]
I tapped on generate link, copied it, opened it up in Brave and; 
![Screenshot_20230601-141559](https://github.com/Myzel394/locus/assets/54247499/cacade7e-3ed6-4384-8875-6496f1df8cad)

**Comment by Myzel394** [comment]
Ohhh I see you are on the webpage. It's actually strange though that the link doesn't load the location - I guess I need to take a look at the site.

However, actually you shouldn't be directed to the site. Instead, the app should open and then you'd be able to import the task. For the moment you can manually copy the link, scroll down on the home screen and tap in "Import Task" and select URL. I'm wondering though why Locus isn't opening.

**Comment by Myzel394** [comment]
I just tested it on my device and for me it's working fine. I'm not sure but maybe DivestOS doesn't support deep linking. Can you open other apps via links @Lamazeva ?

**Comment by Lamazeva** [comment]
I manually went ahead and added locus.cfd as a supported link to open by default (Since DivestOS has it off by default) and it still doesn't redirect me to the app from Brave, I tried opening a new tab and entering in the link, to no avail.

I unchecked "Disable Switch to App" so now Brave redirects me to YouTube Revanced successfully, but for some reason the locus app isn't opening, I'll try to test in main profile with a different browser, but so far everything's been working on the work profile.

**Comment by Myzel394** [comment]
>  I tried opening a new tab and entering in the link

No that won't work, you need to click on the link. You can send it yourself via a messenger for example and when you tap on it, it should open in the app.

**Comment by Lamazeva** [comment]
Alright I'll try that

**Comment by Lamazeva** [comment]
Hah, well its working perfectly when I do it like that, I suppose I was doing it wrong from the start, like with the location

**Comment by Lamazeva** [comment]
All seems well! Great app!
