### ISSUE TITLE
[BUG] Unable to Select Relays

### ISSUE THREAD

**Issue by duncanam** [Myzel394/locus#40]
## OS

* [X] Android
* [ ] iOS

## Android specific
If you ticked `Android`, please specify on which Android flavor this issue happens

* [ ] Samsung Android (Samsung Phones)
* [ ] MIUI (Xiaomi Phones)
* [ ] Stock ROM (Google Phones)
* [ ] Huawei Android (Huawei Phones)
* [X] GrapheneOS
  * [X] I do have Google Play Services installed
* [ ] LineageOS

## Describe the bug
Locus seems great! It looks gorgeous. However, when I go to add a new task and Select Relays, I am seeing at the top of the relay popup tray in red, "An unknown error occured".

## To Reproduce
1. Go to Create Task
2. Tap Select Relays

## Expected behavior
I believe I should see a list of Nostr relays here. 

## Screenshots
![sad_error.png](https://github.com/Myzel394/locus/assets/22781288/15f601ac-54b3-470c-90ec-17211043769a)

## Additional context
I am using the FOSS version, perhaps this could be contributing.

## Priority
Please set a realistic priority on how important this issue is to you. We will fix all bugs, but urgent bugs (such as the app not starting at all for example) are more important than fixing some styles for example.

* [X] Low
* [ ] Medium
* [ ] High
* [ ] Urgent

**Comment by Myzel394** [comment]
@duncanam Can you try accessing the following page in your browser? https://api.nostr.watch/v1/public

**Comment by duncanam** [comment]
> @duncanam but it does **not** work inside the app?

I don't _think_ so, as it is returning the error in the screenshot above. Perhaps I've done something wrong with setup?

**Comment by Myzel394** [comment]
Okay strange something else is causing the error then. I'm currently adding logging functionality. I'd say let's wait until this is implemented, you can update the app then and if the issue still persists, we take another look.

**Comment by duncanam** [comment]
> @duncanam version 0.8.0 has been released. Could you install the update and see if the issue still persists? You can either download via GitHub (https://github.com/Myzel394/locus/releases/tag/v0.8.0) or wait until IzzyOnDroid fetches the update (if I recall correctly, this should happen in about 9 hours).
> 
> If you are still unable to select relays, please go to Settings > Scroll completely down > Press on "Export Logs" > And attach the .zip file here. This file will help me debug your issue and I can fix it as soon as possibe.

You are speedy! This seems to have fixed it- the relays are showing up now for me. Thanks!
