### ISSUE TITLE
[BUG] Tiny Typo in Location Permission Dialog

### ISSUE THREAD

**Issue by duncanam** [Myzel394/locus#49]
## OS

* [X] Android
* [ ] iOS

## Android specific
If you ticked `Android`, please specify on which Android flavor this issue happens

* [ ] Samsung Android (Samsung Phones)
* [ ] MIUI (Xiaomi Phones)
* [ ] Stock ROM (Google Phones)
* [ ] Huawei Android (Huawei Phones)
* [X] GrapheneOS
  * [X] I do have Google Play Services installed
* [ ] LineageOS

## Describe the bug
Truly a small nit: small typo in Location Permissions screen. Last sentence: "necessary to share yur location", " yur"->"your"

## To Reproduce
Upon new app installation.

## Screenshots
![Screenshot_20230608-003040_1.png](https://github.com/Myzel394/locus/assets/22781288/aa094250-1b43-4b85-80e3-16de2aaeb385)

## Priority
Please set a realistic priority on how important this issue is to you. We will fix all bugs, but urgent bugs (such as the app not starting at all for example) are more important than fixing some styles for example.

* [X] Low
* [ ] Medium
* [ ] High
* [ ] Urgent

**Comment by Myzel394** [comment]
Oops, should be fixed now :D Will be included in the next release
