### ISSUE TITLE
[BUG] Relays not working

### ISSUE THREAD

**Issue by gun4qmm7h** [Myzel394/locus#54]
## OS

* [x] Android 
* [ ] iOS

## Android specific
If you ticked `Android`, please specify on which Android flavor this issue happens

* [ ] Samsung Android (Samsung Phones)
* [ ] MIUI (Xiaomi Phones)
* [ ] Stock ROM (Google Phones)
* [ ] Huawei Android (Huawei Phones)
* [x] GrapheneOS
  * [x] I do have Google Play Services installed
* [ ] LineageOS

## To Reproduce
1. Download app (fresh install)
2. Go to make task
3. Try to pick relays
4. Shows loading instead of working

## Expected behavior
Shows options of relays for me to pick

## Screenshots
![Screenshot_20230609-194058](https://github.com/Myzel394/locus/assets/74073434/edbcfc9a-8738-4a46-8980-6e54e116e2cc)

## Priority
Please set a realistic priority on how important this issue is to you. We will fix all bugs, but urgent bugs (such as the app not starting at all for example) are more important than fixing some styles for example.

* [ ] Low
* [ ] Medium
* [ ] High
* [x] Urgent (can't use app without making a task and can't make task without relay)

**Comment by Myzel394** [comment]
@gun4qmm7h Could you upload your logs so that I can take a closer look at your issue? You can extract the logs by: Starting the App > Tapping on the top right settings gear > Scrolling down > Tapping on "Export Logs"

**Comment by gun4qmm7h** [comment]
For some odd reason I can't export logs. When I click on it nothing shows up. I have check my download folder to check and found nothing. Maybe there is a different folder that I can check? Here is a recording in case I'm doing something wrong.  
https://github.com/Myzel394/locus/assets/74073434/d0884126-0115-468e-92d6-2b8006c4bb7b

**Comment by Myzel394** [comment]
Strange, could you try waiting a little bit? If still nothing pops up, you can find the logs here:

1. Open files
2. Tap on top left drawer
3. "Device"
4. Go to "Android" > "data" > "app.myzel394.locus" > "files" > "LocusLogs" > "Logs" >
5. You should see some folders here. If you only see one, tap on it. If you see multiple, tap on the top right three dots > "Sort by" > "Modified (newest first)" and select the first folder
6. Here you should see the logs, attach the latest one here please

I'm very sorry that you are unable to use the app. I hope we can work this out fast.

**Comment by gun4qmm7h** [comment]
[1006202307.log.zip](https://github.com/Myzel394/locus/files/11712255/1006202307.log.zip)
I hope this is the right file. Thank you for the fast response. Less then 10h and you are already working hard on fixing the app. I know that I'm going to love using this app

**Comment by Myzel394** [comment]
@gun4qmm7h Unfortunately the log file only contains the latest logs. I need to update this. Could you try to manually locate the logs using my comment from above (https://github.com/Myzel394/locus/issues/54#issuecomment-1585594769)?

**Comment by gun4qmm7h** [comment]
[archive.zip](https://github.com/Myzel394/locus/files/11712274/archive.zip)

**Comment by Myzel394** [comment]
Thank you. Unfortunately, I couldn't find anything eye-catching. Could you try the following?

1. Try accessing https://api.nostr.watch/v1/public - please let me know if you can access that page
2. Open the Relay Sheet again - wait until an error is shown
3. Export logs again from the settings menu
4. Attach the logs here

**Comment by gun4qmm7h** [comment]
I am able to access [https://api.nostr.watch/v1/public](https://api.nostr.watch/v1/public). Not sure if its broken or not but I shows a one long list of website.
Also I deleted the old logs and cleared the data on the app to hopefully get new useful logs.
[1006202313.log (1).zip](https://github.com/Myzel394/locus/files/11712948/1006202313.log.1.zip)

**Comment by Myzel394** [comment]
@gun4qmm7h was there an error shown in the app?

**Comment by gun4qmm7h** [comment]
No error in the app. I Left it loading in the background for a while without anything showing. Just still the loading icon

**Comment by Myzel394** [comment]
@gun4qmm7h have you enabled the "Network" permission for Locus?

**Comment by gun4qmm7h** [comment]
Yes. Wifi and all other permission are enable

**Comment by DjTimmy001** [comment]
Hi, i have the same problem so i thought i'd share the logs if it can help in any way.
[LocusLogs.zip](https://github.com/Myzel394/locus/files/11713138/LocusLogs.zip)

**Comment by Myzel394** [comment]
@gun4qmm7h and @DjTimmy001 could you try downloading the latest release (https://github.com/Myzel394/locus/releases/tag/v0.8.2)? This update includes a timeout of 30 seconds. When you try to open the relay selection, it should fail after 30 seconds. Could you try if that works, and if yes, export the logs again (hopefully for the last time)?

**Comment by gun4qmm7h** [comment]
[1006202315.log.zip](https://github.com/Myzel394/locus/files/11713190/1006202315.log.zip)

**Comment by DjTimmy001** [comment]
It keeps going. On both lookup providers
[Uploading 10062023_214943_PM_all_[1].zip…]()

**Comment by Myzel394** [comment]
@DjTimmy001 could you try installing the debug build from https://github.com/Myzel394/locus/suites/13513315085/artifacts/742702638, open the selection, wait at least 30 seconds and export the logs again :sweat_smile: ? The zip file contains two files, you need to install "floss-universal-floss.apk"

**Comment by DjTimmy001** [comment]
![Screenshot_20230610-225031](https://github.com/Myzel394/locus/assets/96056362/0a55ebe8-945f-4db2-b102-1590bf269931)

App not installed message, and the screenshot

Btw i don't know that much about how all this works so i apologize if i misunderstand something.

**Comment by Myzel394** [comment]
@DjTimmy001 no worries this was my mistake. You first need to completely uninstall Locus, after that you should be able to install it. btw, what Android flavor are you using (Samsung, Xiaomi, GrapheneOS, etc.)? Maybe this also could cause an issue

**Comment by Myzel394** [comment]
@DjTimmy001 oh wait I think in your case you actually need to install the "GMS" variant, you can find it in the zip file too

**Comment by DjTimmy001** [comment]
I did uninstall the original locus app but neither of those two apk's worked including the gms. 
I am using oneplus android 11

**Comment by Myzel394** [comment]
@DjTimmy001 okay I guess OnePlus only allows signed releases. @gun4qmm7h could you try installing the debug release? It **should** work on GrapheneOS

**Comment by dhammel** [comment]
@Myzel394 I am having this same issue with the floss version, however the GMS variants appears to work fine as for loading the relay section, and the export logs button which dont work in floss version. Would be nice to switch, as I'd rather not rely on anything google. Thought i'd let you know.

~ Pixel 6, stock aosp rooted.

**Comment by Myzel394** [comment]
Okay I found out the issue - thank you very much @dhammel for the hint! I'll fix it now and publish a new release.

**Comment by Myzel394** [comment]
@gun4qmm7h, @DjTimmy001 and @dhammel could you try the newest release https://github.com/Myzel394/locus/releases/tag/v0.8.3? You can either download the release now or wait about 7 hours until IzzyOnDroid updates its repo.

**Comment by gun4qmm7h** [comment]
Thank you very much for the quick fix. I got the relay's working on phone.
Grapheneos w/ google
Pixel 6

**Comment by dhammel** [comment]
@Myzel394 The relay list does work now in floss, however the export logs feature as well as a couple options under share such as share by file don't repond to any input where they do in the GMS variants.

**Comment by Myzel394** [comment]
@dhammel I will take a look at that, thanks for letting me know
