### ISSUE TITLE
[BUG] Some things not working in FLOSS

### ISSUE THREAD

**Issue by Myzel394** [Myzel394/locus#57]
* [ ] Share
* [ ] Export

**Comment by Myzel394** [comment]
Okay after 10 hours of investigation I come to this conclusion:

* It all comes down to `path_provider` as it strangely does not work when gms is removed. I now found out that...
* `nearby_connections`  is the troublemaker, [as it relies on GMS](https://github.com/mannprerak2/nearby_connections/blob/master/android/build.gradle#L35)
* I tried excluding it, but if `nearby_connections` is compiled and gms is excluded, `path_provider` does not work anymore. When `nearby_connections` is NOT added to the project and gms is excluded, `path_provider` works fine - yeah I find that strange too
* I thought about excluding `nearby_connections` for the FLOSS build - but of course Flutter throws an error when a package can't be found

We could now either conditionally import the Flutter widgets where `nearby_connections` is used, or remove the check inside the source code when building for FLOSS (though I would not like to do that), but I was hoping someone else might have a better idea.

@IzzySoft I know that you are not an Android dev, but I was wondering if maybe you have an idea, or know someone that knows someone that knows someone that knows how to deal with such a scenario?

**Comment by IzzySoft** [comment]
The only things I know about this topic can be found [in my snippet here](https://gitlab.com/-/snippets/1896503#flutter-and-geolocation) (also scroll down to the comments where parts of it are discussed). Else I could just suggest to ask developers of other Flutter apps using location stuff and still having made it to F-Droid.org – Like [Every Door](https://github.com/Zverik/every_door) for example…

**Comment by IzzySoft** [comment]
Oh, good find – then let's hope for good progress with that!

**Comment by IzzySoft** [comment]
Oh, cool! Do you think your work-around should be documented in my [F-Droid snippet](https://gitlab.com/-/snippets/1896503) in connection with the GeoLocator case?

**Comment by Myzel394** [comment]
I think that would be a good idea. Should I write the docs?

**Comment by IzzySoft** [comment]
That'd be great, thanks! You could add it to the snippet as comment for now.

The snippet might not be ideal, true – I've thought about moving it to my wiki and then link to the snippet (bi-directionally) for comments etc, but am not sure if that would make the thing even more complicated. The link to that snippet is widely shared already, so that's where many folks look for it already…

**Comment by Myzel394** [comment]
Here's the comment :)

https://gitlab.com/-/snippets/1896503#note_1435110124

**Comment by IzzySoft** [comment]
Thanks! Already received the notification from GitLab. Linked to your comment from the "Flutter hints" section to make it easier to find.
