### ISSUE TITLE
[BUG] Is this an alternative to Life360?

### ISSUE THREAD

**Issue by codeonblocks** [Myzel394/locus#70]
Sorry to leave a nonexistent issue, but I'm having a hard time wrapping my head around how this app works.

Is this a replacement for location sharing apps like Life360/FindMyFriends?

**Comment by Myzel394** [comment]
Hey @codeonblocks

I'm sorry but I don't know neither of these apps. My goal was to provide an alternative to Google's and Apple's Share My Location functionality. So you can share your location for a specific amount of time or during specific hours of the day.

**Comment by codeonblocks** [comment]
> Hey @codeonblocks
> 
> I'm sorry but I don't know neither of these apps. My goal was to provide an alternative to Google's and Apple's Share My Location functionality. So you can share your location for a specific amount of time or during specific hours of the day.

Life360 is an app that allow you to share your location with family members so that they can know where you are in case of an emergency. Does Locus do this as well, and can you share your location indefinitely until you remove the task?

**Comment by Myzel394** [comment]
> Does Locus do this as well, and can you share your location indefinitely until you remove the task?

Yes you can share your location indefinitely until you manually stop or remove it. You can also share it for a given amount, like for 2 hours, for 3 days etc.

Emergency location sharing is currently not implemented, but this is a planned feature (#60). not sure when this will be released, as I have to figure out how to properly implement this with Android (so that in case of an emergency, Locus automatically sends the location).

**Comment by Myzel394** [comment]
@codeonblocks if you have the app open in the task manager, it will fetch the app every two minutes. You can swipe the app away to make it query less often. But you just brought me a new idea for a feature: Battery Save mode! I'll add this to the next release.

**Comment by Myzel394** [comment]
@codeonblocks I have added battery saver mode to [v0.10.1](https://github.com/Myzel394/locus/releases/tag/v0.10.1). Can you check if this reduces your battery drain? (make sure to close the app / swipe the app away, to make sure it's not updating in real time)

**Comment by Myzel394** [comment]
> Awesome! Is the task manager where you swipe up and hold and it shows you all the apps that are currently running and you can swipe them away to close them?

Exactly! If you keep Locus open, it will update the location in real time. If you close it, it will update it less frequently.

> Also, how long does it take for the update to show up on your IzzyOnDroid repo?

Actually it's not my repo, so I have no control over it, but as far as I know, Izzy updates it at 11:00 AM (in your local time according to GitHub).

> I'd suggest maybe looking into what that app is since you could possibly help market this app by showing how it could be a privacy-focused replacement for it.

I'll do that! As soon as I get a credit card, I'll also publish the app on Google Play (and maybe on the App Store) too, so then Locus will be easier to access! :D

**Comment by codeonblocks** [comment]
> Exactly! If you keep Locus open, it will update the location in real-time. If you close it, it will update it less frequently.

Now that I've updated it to v0.10.1 & turned on Battery Saver Mode, it doesn't seem to update in the background at all. Before when I would open up the app, it would trigger a location update, but now it doesn't do that either.

How often is it supposed to update the location with the BSM? 
What would cause a new location update trigger to happen with and without BSM?

**Comment by Myzel394** [comment]
> How often is it supposed to update the location with the BSM?
What would cause a new location update trigger to happen with and without BSM?

Locus will only update once an hour if the battery saver mode is enabled. I don't understand your second question - Locus automatically updates your location. Without Battery Saver Mode, this should happen about every 15 minutes.

**Comment by Myzel394** [comment]
@codeonblocks ooops I just realized I pushed some unwanted changes to 0.10.1 - 0.10.2 contains a fix for this - if you use the GMS version, the location should be fetched now correctly in 0.10.2

**Comment by codeonblocks** [comment]
I actually use the FLOSS version. In v0.10.1 it seems that it doesn't poll for locations anymore, and I'm not sure if its this app but something is shredding through my battery life, even while the phone is locked throughout the night and everything is swipped away in the task manager.
![Screenshot_20230624-084052](https://github.com/Myzel394/locus/assets/32179921/b7838354-f2cd-48b6-97d5-ca7154651107)

I can provide you with logs if you need, but I don't know how to do that.

**Comment by Myzel394** [comment]
> I actually use the FLOSS version. In v0.10.1 it seems that it doesn't poll for locations anymore

That's strange, it should fetch the location once per hour with battery saver mode. Can you check if you get any location? You can do so by going into the settings (top right gear icon), then on "Verify location access" and then run the check. You may need to go outside to get proper location, the FLOSS version seems to have troubles getting the location inside buildings (at least in Europe).

> I'm not sure if its this app but something is shredding through my battery life, even while the phone is locked throughout the night and everything is swipped away in the task manager.

I hope it's not Locus :sweat_smile:, at least for me it's not draining that much battery (I'm using Android too). As a general hint from my side, you could [try installing AcuBattery](https://play.google.com/store/apps/details?id=com.digibites.accubattery&hl=en_US). This app gives you much more details on how long your battery lasts, what app is draining how much battery, etc. Note that it needs some days to properly calibrate itself.

> I can provide you with logs if you need, but I don't know how to do that.

That would be awesome! You can share the logs by going into the settings (Locus' settings, not Android settings), scrolling completely down and at the bottom you should see a button with the label "Export Logs". Tap that and upload the shared logs here.

Sorry for the inconveniences, I hope I can fix these issue for you quickly.

**Comment by codeonblocks** [comment]
1. I was able to verify my location & its working, but it doesn't seem to get it in the background like before on v0.10.0

2. Thanks for the recommendation.
3. No worries! I'm a developer too so I like to help. Here are my logs:
[LocusLogs.zip](https://github.com/Myzel394/locus/files/11857240/LocusLogs.zip)

**Comment by codeonblocks** [comment]
It seems to be polling for locations again after doing the location verification, but its doing it every 2-5 mins now even when swipped away or with the Battery Saver mode on in the app (BSM is not on in the phone)

**Comment by Myzel394** [comment]
Hey @codeonblocks quick question:

How did you manage to get a timeline of location usages (https://github.com/Myzel394/locus/issues/70#issuecomment-1604376945)? I was trying to find it in the settings, but couldn't find such an option

**Comment by codeonblocks** [comment]
> Hey @codeonblocks quick question:
> 
> How did you manage to get a timeline of location usages ([#70 (comment)](https://github.com/Myzel394/locus/issues/70#issuecomment-1604376945))? I was trying to find it in the settings, but couldn't find such an option

I use GrapheneOS which is based off of AOSP. I went into:
Settings -> Location -> Recent Location Access

Also:
Settings -> Privacy -> Privacy Dashboard -> Location
