### ISSUE TITLE
[FEATURE] Clearer location history

### ISSUE THREAD

**Issue by Titaniumtown** [Myzel394/locus#80]
**Is your feature request related to a problem? Please describe.**
Seeing the history of someone's location is difficult due to the lack of lines between locations and the vauge circles that indicate location.

**Describe the solution you'd like**
Clear lines and points between previous locations.

**Comment by Titaniumtown** [comment]
Thanks! I'll make sure to test it when the GitHub release is pushed so obtanium grabs it! @Myzel394

**Comment by Myzel394** [comment]
@Titaniumtown good idea! I forgot to migrate it to Apple Maps though, so I'll need some time to update it there as well, but the update should come in the next days

**Comment by Titaniumtown** [comment]
Ok I downloaded the latest GitHub actions build. Big improvement! But the lines aren't very thick and are not very opaque, making it difficult to see. Also it is not shown when selecting a share directly and going to history, the normal blue circles are shown.

**Comment by Myzel394** [comment]
@Titaniumtown thanks for the early feedback! I'm not sure how thick the lines should be as I was worried when people have a lot of shares they might find them too thick - but we could use thick lines if it's just a few shares and thin ones if it's multiple. 

>  and are not very opaque

and

> Also it is not shown when selecting a share directly and going to history, the normal blue circles are shown.

yes I need to address that, you are very early :D

**Comment by Titaniumtown** [comment]
I know! Just giving feedback lol
