### ISSUE TITLE
[BUG] Restoring Locus data doesn't work

### ISSUE THREAD

**Issue by Titaniumtown** [Myzel394/locus#82]
## OS
* [x] Android
* [ ] iOS

## Android specific
* [ ] Samsung Android (Samsung Phones)
* [ ] MIUI (Xiaomi Phones)
* [ ] Stock ROM (Google Phones)
* [ ] Huawei Android (Huawei Phones)
* [ ] GrapheneOS
  * [ ] I do have Google Play Services installed
* [x] LineageOS

## Describe the bug
When importing locus data, nothing happens and nothing is restored from the exported data.

## To Reproduce
1. Export locus data in settings
2. Delete app
3. Reinstall app
4. Load exported json file and import it in settings

## Expected behavior
Location shares, history, and the ability to view other shares should be restored.

## Priority
* [ ] Low
* [ ] Medium
* [X] High
* [ ] Urgent
 
## App Version
Version 0.12.1 (FLOSS)
 
## Logs
[18072023_222644_PM_all_[1].zip](https://github.com/Myzel394/locus/files/12088761/18072023_222644_PM_all_.1.zip)

**Comment by Myzel394** [comment]
@Titaniumtown I know this might sound a bit funny, but.... could you try restarting Locus after importing the data? I just tried it locally and it worked for me after restarting Locus

**Comment by Titaniumtown** [comment]
Oh it works now, still an issue though! But less so lol

**Comment by Myzel394** [comment]
> No no, I meant that it shouldn't require a restart or the user should be promoted to restart the app

Ahh I see! I'll try to make it work without a restart, but maybe one is required

**Comment by Myzel394** [comment]
Added a note in `0.13.0`
