### ISSUE TITLE
active?

### ISSUE THREAD

**Issue by degaur** [Myzel394/locus#84]
Hi,
The open project is still active and maintainded ?

**Comment by pvxcooper** [comment]
The last commit was 7 hours ago and the latest release was just 2 days ago. I'm not sure why you would think this.

**Comment by degaur** [comment]
Hi @pvxcooper, thanks!

**Comment by Myzel394** [comment]
@degaur you were probably confused because I said that one of my other app is not maintained anymore (https://github.com/Myzel394/relieve/issues/1), this is because that app was just part of a hackathon - but Locus isn't built based on any special event and I'll keep maintaining it :D
