### ISSUE TITLE
Location text not refreshing in bottom space when clicking on other tag

### ISSUE THREAD

**Issue by mrdanleey** [Myzel394/locus#85]
## OS

* [x] Android
* [ ] iOS

## Android specific
If you ticked `Android`, please specify on which Android flavor this issue happens

* [x] Samsung Android (Samsung Phones)
* [ ] MIUI (Xiaomi Phones)
* [ ] Stock ROM (Google Phones)
* [ ] Huawei Android (Huawei Phones)
* [ ] GrapheneOS
  * [ ] I do have Google Play Services installed
* [x] LineageOS

## Describe the bug
When cliccking on a pin at the map view the location of the pin is shown in the white space at the bottom on the screen. When I click on another pin on the map the location is not refreshed at this space. The location where the pin is on the map s correct so it is only the text that is not refreshing

## To Reproduce
You got to have to pins on the map, click on the first pin to see the location text in the white space at the bottom. Now click on the other pin and you see that the text is not changing in the space at the bottom.

## Priority
Please set a realistic priority on how important this issue is to you. We will fix all bugs, but urgent bugs (such as the app not starting at all for example) are more important than fixing some styles for example.

* [ ] Low
* [x] Medium
* [ ] High
* [ ] Urgent
 
## App Version
Newest version, Foss and GMS version.

**Comment by Myzel394** [comment]
> You got to have to pins on the map, click on the first pin to see the location text in the white space at the bottom. Now click on the other pin and you see that the text is not changing in the space at the bottom.

When you tap on the pin a popup should be shown above it, did you press on "Show details" then? What sheet do you see at the bottom? A sheet that says something like "No active shares" or "5 active shares" or a sheet with the current location?

**Comment by mrdanleey** [comment]
I see only the white screen at the bottom when I press a pin. On that screen the current location is shown.

**Comment by Myzel394** [comment]
What pins do you mean? Do you mean a pin on the map (green in this example) or above the map (red, yellow, blue)?

![image](https://github.com/Myzel394/locus/assets/50424412/1145333b-07f2-4052-86ed-df3b6635219b)

**Comment by mrdanleey** [comment]
> What pins do you mean? Do you mean a pin on the map (green in this example) or above the map (red, yellow, blue)?
> 
> ![image](https://github.com/Myzel394/locus/assets/50424412/1145333b-07f2-4052-86ed-df3b6635219b)
> 

The red, green and blue one

**Comment by Myzel394** [comment]
I guess you mean red, blue and yellow, don't you? :D

**Comment by mrdanleey** [comment]
> I guess you mean red, blue and yellow, don't you? :D

Yes, I misred the colors 😄

**Comment by Myzel394** [comment]
I'm not really sure why this is the case for you, but since other markers shouldn't been shown when one is selected, I'll need to fix this, which should close this issue then
