### ISSUE TITLE
[FEATURE] Better path tracing and history

### ISSUE THREAD

**Issue by Titaniumtown** [Myzel394/locus#86]
**Is your feature request related to a problem? Please describe.**
Previous locations can be unclear when a task may span days. This compounded with GPS inaccuracies make it difficult to read.

**Describe the solution you'd like**
It would be good to have a configurable displayed history and an ability to discard or hide previous history. Also maybe like a timeline or something being easily accessible and shown on the main screen.

This in combination with some smart merging of location points when they are extremely close together could it more clear to the end user so it doesn't look like a jumbled mess when GPS inaccuracies make the true location unclear.

**Comment by Myzel394** [comment]
> This in combination with some smart merging of location points when they are extremely close together

This sounds like a good idea, I'll see what I can do about that!

> Previous locations can be unclear when a task may span days

You should only be able to see the last 24 hours, can you see more? If yes, then that's a bug :D

**Comment by Titaniumtown** [comment]
> You should only be able to see the last 24 hours, can you see more? If yes, then that's a bug :D

My bad, it is limited correctly, but it can still be a lot visually.

**Comment by Myzel394** [comment]
@Titaniumtown I have opened PR #88 to fix this issue. Would you like to test the changes out before we will migrate and publish them? :)

**Comment by Korb** [comment]
An idea for the future, if a similar question is still raised: the track can be made gradient with a gradual transition from full opacity (the latest data) to almost full transparency (the oldest). And, of course, add the ability to turn on and off the display of location accuracy circles.
