### ISSUE TITLE
Can't select relays

### ISSUE THREAD

**Issue by deelite** [Myzel394/locus#95]
## OS

* [x ] Android
* [ ] iOS

## Android specific
Android 13, patch Level 2023/07/01, Samsung Galaxy S21 FE

* [ x] Samsung Android (Samsung Phones)
* [ ] MIUI (Xiaomi Phones)
* [ ] Stock ROM (Google Phones)
* [ ] Huawei Android (Huawei Phones)
* [ ] GrapheneOS
  * [ ] I do have Google Play Services installed
* [ ] LineageOS

## Describe the bug
When creating a share I can't select any relay. 

## To Reproduce
1. Shares overview
2. Create new(?) - I can't see anything on the button
3. Giving a name
4. Select relays
5. No relays will be listed

## Expected behavior
I think I will get a list of relays to select

## Screenshots
![Screenshot_20230812_100104](https://github.com/Myzel394/locus/assets/1825933/0253b4c8-fe50-45b1-a8d0-1b6910d66f1e)
![Screenshot_20230812_095919](https://github.com/Myzel394/locus/assets/1825933/a9e37df5-634a-4084-9c61-8655783c4784)

## Priority
Please set a realistic priority on how important this issue is to you. We will fix all bugs, but urgent bugs (such as the app not starting at all for example) are more important than fixing some styles for example.

* [ ] Low
* [ ] Medium
* [ ] High
* [ ] Urgent
 
## App Version
Please add the version you have installed here. You can find the version by opening Locus > Tap on the top right settings icon > Scroll completely down > At the very bottom you can find your version with your flavor, for example "Version 0.8.1 (GMS)" or "Version 0.7.0 (FLOSS)".

**Comment by Myzel394** [comment]
There seems to be a problem with the API, I added a comment at https://github.com/dskvr/nostr-watch/issues/362

**Comment by GsnailG** [comment]
I also have this problem with an S10. Perhaps it is downloading all the relays but it might take forever. Would a progress bar instead of a spinny thing work well?

**Comment by Myzel394** [comment]
Should be fixed in `v0.14.2`
