### ISSUE TITLE
[BUG] Unable to share location

### ISSUE THREAD

**Issue by trav90** [Myzel394/locus#96]
## OS

* [x] Android
* [ ] iOS

## Android specific
If you ticked `Android`, please specify on which Android flavor this issue happens

* [x] Samsung Android (Samsung Phones)
* [ ] MIUI (Xiaomi Phones)
* [ ] Stock ROM (Google Phones)
* [ ] Huawei Android (Huawei Phones)
* [ ] GrapheneOS
  * [ ] I do have Google Play Services installed
* [ ] LineageOS

## Describe the bug
I am unable to actually share my location. I am using a freshly installed FLOSS build from Izzy's F-Droid repo on a Samsung Galaxy A14 running Android 13. I am able to see and verify my location in the app, but when I click on "Share Location" I get a "An unknown error occurred" and nothing is copied to the clipboard.

## To Reproduce
1. Open app and wait for it to display current location
2. Go to Share Location
3. Select either "Share until I turn it off" or "Share for the following time"
4. Tap "Share" button
5. See error

## Expected behavior
A shareable link is copied to my clipboard that can then be sent to someone.

## Screenshots
![Screenshot_20230817_135607](https://github.com/Myzel394/locus/assets/10595410/8faab2ef-3ef9-453e-ab6d-ff68101a2238)

## Priority
Please set a realistic priority on how important this issue is to you. We will fix all bugs, but urgent bugs (such as the app not starting at all for example) are more important than fixing some styles for example.

* [ ] Low
* [X] Medium
* [ ] High
* [ ] Urgent
 
## App Version
Version 0.14.1 (FLOSS)
 
## Logs
[17082023_140502_PM_all_%5B4%5D.zip](https://github.com/Myzel394/locus/files/12372806/17082023_140502_PM_all_.5B4.5D.zip)

**Comment by Myzel394** [comment]
Yes this is already known in #95. Unfortunately, this seems to be a problem with the upstream API :/ I'm very sorry for that. I will push out a fix in the next few weeks, but I'm quite busy at the moment.

**Comment by Myzel394** [comment]
> No worries at all! My apologies that this was already known.

No worries, it's not your task to keep track of the issues - that is my responsibility! :D 

> Thanks for your time and I will check back periodically for a fix

Actually, let's fix this today! I got a bit of free time now, I'll send out an update in a few hours. Feel free to ping me if I don't release an update soon.

**Comment by trav90** [comment]
Wow, that would be awesome! I really appreciate it!

**Comment by Myzel394** [comment]
Should be fixed in `v0.14.2`

**Comment by trav90** [comment]
v0.14.2 is working great! Thanks again so much! God bless.
