### ISSUE TITLE
[BUG] Cannot share location

### ISSUE THREAD

**Issue by mikoducky** [Myzel394/locus#97]
## OS

* [X] Android
* [ ] iOS

## Android specific
If you ticked `Android`, please specify on which Android flavor this issue happens

* [ ] Samsung Android (Samsung Phones)
* [ ] MIUI (Xiaomi Phones)
* [ ] Stock ROM (Google Phones)
* [ ] Huawei Android (Huawei Phones)
* [X] GrapheneOS
  * [ ] I do have Google Play Services installed
* [ ] LineageOS

## Describe the bug
I think this is a bug. I create a share, then try to generate a link, but nothing happens. If I go to the details, and try to share the link or a qr code, again, nothing happens. Nothing sent to the clipboard either.

## To Reproduce
1. Create share
2. Open share details
3. Try to share qr code or link
4. It does nothing

## Expected behavior
I would expect a window to pop up with the qr code or a link I can copy to text to someone.

## Additional context
Just running graphene os on a pixel 6a here. It's basically the gold standard for de-googled Android, right?

## Priority
I'd really like to see it fixed in the next couple weeks before I go to Pennsylvania, so I can use this phone to share location instead of stupid iphone.

* [ ] Low
* [X] Medium
* [ ] High
* [ ] Urgent
 
## App Version
Version 0.14.2 (FLOSS)

I'll definitely donate if you guys can get it working for me.

**Comment by Myzel394** [comment]
Can you send me your log files?

**Comment by mikoducky** [comment]
Sure thing. Please see attached.

[29082023_000556_AM_all_[12].zip](https://github.com/Myzel394/locus/files/12463787/29082023_000556_AM_all_.12.zip)

**Comment by Myzel394** [comment]
Okay so there seems to be an issue with the selected Nostr relays. I haven't figured out a way to reliably detect which Nostr relays are safe to use and which aren't. While I'll figure that out, you can simply change your relays in the meantime to be able to share your location correctly :D

**Comment by mikoducky** [comment]
I had to keep choosing different relays (ones without nostr in the name) and it still didn't work. I saw one said cloudflare, so I swapped that as well, since those guys suck. It finally gave me a url, which... also doesn't work lol. Here's the screenshot:
![Screenshot_20230829-082346](https://github.com/Myzel394/locus/assets/74574472/c2307f0d-eed4-43df-ac43-69435026d52f)

I cannot zoom out or in, and when I look at the url after loading, everything has been stripped off. Using firefox.

**Comment by Myzel394** [comment]
> I had to keep choosing different relays (ones without nostr in the name) and it still didn't work

If you found one that's working now, that's good. I'll release an update soon that will improve the selection process.

> It finally gave me a url, which... also doesn't work lol

The site does not work on mobile yet, can you try opening it on the desktop?

> and when I look at the url after loading, everything has been stripped off

That's intended for privacy reasons to avoid one leaking the link to others.

**Comment by mikoducky** [comment]
I'll try the desktop site when I get home. Is there a plan on getting that to work on mobile? My dad has an iphone (my fault) and I know he won't be willing to build any apps. He'd likely be ok with using the page on his desktop.
I'm an adult, and when I travel alone, my parents want to track me, but when they do the same, it's suddenly not a problem.

**Comment by Myzel394** [comment]
> Is there a plan on getting that to work on mobile?

Yes, but not in the near future unfortunately :/

> My dad has an iphone (my fault) and I know he won't be willing to build any apps

If I recall correctly, the EU wants to force Apple to allow third-party app stores soon. When that's the case, I'll see if I can publish Locus in one of those stores.

**Comment by Myzel394** [comment]
@Korb you don't have any nostr relays selected. Make sure to select a few. If the issue still persists, try changing them, as there currently seems to be a problem with some nostr relays.

BTW, I saw your other issues with your great ideas :D I will take a look at each at them later. I'll be quite busy in the next few days, so bear with me if I don't respond quickly :D

**Comment by Korb** [comment]
@Myzel394, you are right, thanks.  It might make sense in a situation like mine to gray the "Share Location" button and mark the "Nostr Relays" field with a red frame or an asterisk as a required field and the reason for greying the "Share Location" button.

**Comment by Myzel394** [comment]
@Korb I'm a bit confused on how you even ended up here, because you actually shouldn't be able to create or update a share with our any relays. Can you tell me how you created this share? Via the quick share button or on the shares overview?

**Comment by Myzel394** [comment]
@mikoducky is this issue still occurring in the new version?

**Comment by mikoducky** [comment]
It seems to be fine now. I updated, but the app refused to open, so I uninstalled, re-installed, and it acts normal. I was even able to post the link to my mobile browser and see the location on the map, so if you messed with that, it's better now.

**Comment by Myzel394** [comment]
@mikoducky okay I'm glad it's working for you now ^^ if the issue happens again, feel free to reopen the issue
